import type { Room } from "../shared/types";

export const TEST_ROOM: Room = {
  id: "test-room-1",
  name: "Test Chamber",
  description: "A simple room to test movement, collision, and interactions.",
  map: {
    width: 2400,
    height: 1800,
    backgroundColor: "#e8e8e8",
    playerSpawn: { x: 1200, y: 900 },
  },
  player: {
    speed: 200,
    size: { width: 28, height: 28 },
    interactionReach: 20,
  },
  collisionZones: [
    { id: "wall-top", bounds: { x: 0, y: 0, width: 2400, height: 32 } },
    { id: "wall-bottom", bounds: { x: 0, y: 1768, width: 2400, height: 32 } },
    { id: "wall-left", bounds: { x: 0, y: 0, width: 32, height: 1800 } },
    { id: "wall-right", bounds: { x: 2368, y: 0, width: 32, height: 1800 } },
    { id: "pillar-1", bounds: { x: 400, y: 300, width: 64, height: 64 } },
    { id: "pillar-2", bounds: { x: 1100, y: 300, width: 64, height: 64 } },
    { id: "pillar-3", bounds: { x: 400, y: 800, width: 64, height: 64 } },
    { id: "pillar-4", bounds: { x: 1100, y: 800, width: 64, height: 64 } },
    { id: "table-center", bounds: { x: 650, y: 350, width: 300, height: 150 } },
  ],
  objects: [
    {
      id: "obj-safe",
      type: "safe",
      name: "Safe",
      position: { x: 200, y: 100 },
      size: { width: 64, height: 64 },
      zIndex: 0,
      hidden: false,
      collectible: false,
      collision: { x: 200, y: 100, width: 64, height: 64 },
      interactionRadius: 60,
      properties: {},
    },
    {
      id: "obj-key",
      type: "key",
      name: "Golden Key",
      position: { x: 1300, y: 900 },
      size: { width: 32, height: 32 },
      zIndex: 0,
      hidden: false,
      collectible: true,
      collision: null,
      interactionRadius: 50,
      properties: {},
    },
    {
      id: "obj-door",
      type: "door",
      name: "Exit Door",
      position: { x: 750, y: 40 },
      size: { width: 80, height: 60 },
      zIndex: 0,
      hidden: false,
      collectible: false,
      collision: { x: 750, y: 40, width: 80, height: 60 },
      interactionRadius: 60,
      properties: {},
    },
    {
      id: "obj-note",
      type: "note",
      name: "Mysterious Note",
      position: { x: 500, y: 700 },
      size: { width: 40, height: 40 },
      zIndex: 0,
      hidden: false,
      collectible: false,
      collision: null,
      interactionRadius: 50,
      properties: {},
    },
  ],
  triggers: [
    {
      id: "trg-read-note",
      event: "interact",
      sourceId: "obj-note",
      conditions: [],
      actions: [
        {
          type: "show_message",
          message:
            "The note reads: 'The key is hidden in the southeast corner.'",
        },
      ],
    },
    {
      id: "trg-collect-key",
      event: "interact",
      sourceId: "obj-key",
      conditions: [],
      actions: [
        { type: "add_to_inventory", targetId: "obj-key" },
        { type: "show_message", message: "You picked up the Golden Key." },
      ],
    },
    {
      id: "trg-use-key-on-door",
      event: "use_item_on",
      sourceId: "obj-door",
      itemId: "obj-key",
      conditions: [{ type: "has_item", itemId: "obj-key" }],
      actions: [
        { type: "remove_from_inventory", targetId: "obj-key" },
        { type: "win" },
      ],
    },
    {
      id: "trg-safe-locked",
      event: "interact",
      sourceId: "obj-safe",
      conditions: [],
      actions: [
        {
          type: "show_message",
          message: "The safe is locked. You need to find something...",
        },
      ],
    },
  ],
  winCondition: { type: "trigger", triggerId: "trg-use-key-on-door" },
};
