/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as BuildRouteImport } from "./routes/build";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PlayRouteImport } from "./routes/play";

const PlayRoute = PlayRouteImport.update({
	id: "/play",
	path: "/play",
	getParentRoute: () => rootRouteImport,
} as any);
const BuildRoute = BuildRouteImport.update({
	id: "/build",
	path: "/build",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/build": typeof BuildRoute;
	"/play": typeof PlayRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/build": typeof BuildRoute;
	"/play": typeof PlayRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/build": typeof BuildRoute;
	"/play": typeof PlayRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/build" | "/play";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/build" | "/play";
	id: "__root__" | "/" | "/build" | "/play";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	BuildRoute: typeof BuildRoute;
	PlayRoute: typeof PlayRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/play": {
			id: "/play";
			path: "/play";
			fullPath: "/play";
			preLoaderRoute: typeof PlayRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/build": {
			id: "/build";
			path: "/build";
			fullPath: "/build";
			preLoaderRoute: typeof BuildRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	BuildRoute: BuildRoute,
	PlayRoute: PlayRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
